import { isBuiltinLanguage, type BuiltinLanguage, type Language, type TargetAbi } from "./types.ts";
import { FORGE_CONTRACT_VERSION } from "./contract.ts";

export interface ToolchainDefinition {
  readonly language: BuiltinLanguage;
  readonly label: string;
  readonly artifact: "wasm" | "runtime-bundle";
  readonly compilerPackages: readonly string[];
  readonly runtimePackage?: string;
  readonly targets: readonly TargetAbi[];
  readonly version: string;
  readonly note: string;
}

export const CLANG_VERSION = "22.0.0-git20542-10";
export const CLANG_PACKAGE = `wasm-oj/clang@${CLANG_VERSION}`;
export const CLANG_PACKAGE_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.webc.gz.bin`;
export const CLANG_CC1_PINS_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.cc1-pins.json`;
export const CLANG_MANIFEST_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.manifest.json`;
export const CLANG_COMPRESSED_PACKAGE_SHA256 = "7f10d90b8e52b270f04874641a1d0bf9e94e85b4f6c7573a774cebbc6d32552a";
/** SHA-256 after browser-side gzip decompression. */
export const CLANG_PACKAGE_SHA256 = "21ded33b9c6d4e1aaad5528c940bdaf6c3e84be77ea8f522f018ca7289a2a224";
/** SHA-256 of the pinned cc1/wasm-ld argv manifest; regenerated by scripts/pin-clang-cc1-argv.mjs. */
export const CLANG_CC1_PINS_SHA256 = "4583b167dcac4bc1766c8378e0761b32e747ea614f24a1dcf2d8e8b0dc116029";
export const CLANG_MANIFEST_SHA256 = "681dc3a98aa98c8902cd17bb5d155b8771d650f2ac64f9552f45d524a2b955fd";
export const PYTHON_VERSION = "3.14.6";
export const PYTHON_PACKAGE_SHA256 = "67ffc49c3df1c874ff8407bc7972b3ae951b0ba564687e9eb1ea2cb82f77cf86";
export const PYTHON_PACKAGE_SPECIFIER = `wasm-oj/cpython@${PYTHON_VERSION}`;
export const PYTHON_PACKAGE = `${PYTHON_PACKAGE_SPECIFIER}#sha256:${PYTHON_PACKAGE_SHA256}`;
export const PYTHON_PACKAGE_ASSET_PATH = `/toolchains/python-${PYTHON_VERSION}-wasip1.webc.gz.bin`;
export const PYTHON_PACKAGE_MANIFEST_ASSET_PATH = `/toolchains/python-${PYTHON_VERSION}-wasip1.manifest.json`;
export const PYTHON_COMPRESSED_PACKAGE_SHA256 = "f8ada27da0b9bbe8a4e06736f320d71f6aca33876e8a0fd8894c5733972ba3c5";
export const PYTHON_PACKAGE_MANIFEST_SHA256 = "ab6d91af39227ed8b0655b56f0b8340d67864d6397fa933df76e1b24a9134161";
export const PYTHON_RUNTIME_FILES_ARCHIVE_SHA256 = "8aeae854650b5cc5af015dcfacb79f974d5a6997110c98b083cf4d618e20e4ba";
export const QUICKJS_VERSION = "0.15.1";
export const QUICKJS_PACKAGE = `wasm-oj/quickjs-ng@${QUICKJS_VERSION}`;
export const QUICKJS_ASSET_PATH = `/toolchains/quickjs-${QUICKJS_VERSION}.wasm.gz.bin`;
export const QUICKJS_ASSET_SHA256 = "5b1419b8d65d2b910b61954071e28d99ce1fd401b5dd9b47e2bf16552f9ff582";
export const TYPESCRIPT_VERSION = "7.0.2";
export const TYPESCRIPT_ASSET_PATH = `/toolchains/typescript-${TYPESCRIPT_VERSION}.wasm.gz.bin`;
export const TYPESCRIPT_ASSET_SHA256 = "287c1a1e48179014821b8acbaa78000c17df4d072cab2cb9e8d7477cd55878f7";
export const RUST_VERSION = "1.91.1-dev";
export const RUST_PACKAGE_ASSET_PATH = `/toolchains/rust-${RUST_VERSION}.webc.gz.bin`;
export const RUST_PACKAGE_MANIFEST_ASSET_PATH = `/toolchains/rust-${RUST_VERSION}.manifest.json`;
export const RUST_COMPRESSED_PACKAGE_SHA256 = "cfbdadc67be1315e735aa55bdf8a5a0d00171982a023fefcf7ba586127753887";
/** SHA-256 after browser-side gzip decompression. */
export const RUST_PACKAGE_SHA256 = "765de8d68d03078e79f69f49dec0dcab1ff96fe3bbe5e9eafebb2ce61a39d3ee";
export const RUST_PACKAGE_MANIFEST_SHA256 = "14715bd4eeb7dfe9dc806e7f28f404a87f590728f4c622f5de5b71857ceacc21";
export const GO_VERSION = "1.26.5";
export const GO_PACKAGE_ASSET_PATH = `/toolchains/go-${GO_VERSION}-wasip1.webc.gz.bin`;
export const GO_PACKAGE_MANIFEST_ASSET_PATH = `/toolchains/go-${GO_VERSION}-wasip1.manifest.json`;
export const GO_STANDARD_LIBRARY_ASSET_PATH = `/toolchains/go-${GO_VERSION}-wasip1.stdlib.gz.bin`;
export const GO_COMPRESSED_PACKAGE_SHA256 = "70a7e359884b09b2e1a622d6ac5cd6e31c334aab519e6dd80dff5e040a9e09e4";
export const GO_PACKAGE_SHA256 = "c3a97934b6a83fefdea5c31f99141f70f76189eedc9ec0fa9ccd41302e50963b";
export const GO_PACKAGE_MANIFEST_SHA256 = "20bd57867439708500216da85e5c87e7f253bc797bb50873dc08981afc4d9e1a";
export const GO_COMPRESSED_STANDARD_LIBRARY_SHA256 = "78a4531121a78c3fca5b3ed0a24a0c1c4f9ac0b330d0d38730768cee7f174d68";
export const GO_STANDARD_LIBRARY_SHA256 = "0f52f7f37cc7bec08422c64607cf695e33a80852ce0b39d88a3bbe7d09a87b5a";
export const GO_COMPILER_SHA256 = "9e557f5b86961fd604217d7521461c5d2b7322e383fa30dead5669b77db12201";
export const GO_LINKER_SHA256 = "2eefca10af935a307ab7946447146bd30e0ea0fb5460be54dc1c55844d155580";

export const PINNED_TOOLCHAIN_ASSET_SHA256 = Object.freeze<Record<string, string>>({
  [CLANG_PACKAGE_ASSET_PATH]: CLANG_COMPRESSED_PACKAGE_SHA256,
  [CLANG_CC1_PINS_ASSET_PATH]: CLANG_CC1_PINS_SHA256,
  [CLANG_MANIFEST_ASSET_PATH]: CLANG_MANIFEST_SHA256,
  [PYTHON_PACKAGE_ASSET_PATH]: PYTHON_COMPRESSED_PACKAGE_SHA256,
  [PYTHON_PACKAGE_MANIFEST_ASSET_PATH]: PYTHON_PACKAGE_MANIFEST_SHA256,
  [QUICKJS_ASSET_PATH]: QUICKJS_ASSET_SHA256,
  [TYPESCRIPT_ASSET_PATH]: TYPESCRIPT_ASSET_SHA256,
  [RUST_PACKAGE_ASSET_PATH]: RUST_COMPRESSED_PACKAGE_SHA256,
  [RUST_PACKAGE_MANIFEST_ASSET_PATH]: RUST_PACKAGE_MANIFEST_SHA256,
  [GO_PACKAGE_ASSET_PATH]: GO_COMPRESSED_PACKAGE_SHA256,
  [GO_PACKAGE_MANIFEST_ASSET_PATH]: GO_PACKAGE_MANIFEST_SHA256,
  [GO_STANDARD_LIBRARY_ASSET_PATH]: GO_COMPRESSED_STANDARD_LIBRARY_SHA256,
});

const TOOLCHAIN_CONTENT_SHA256: Readonly<Record<BuiltinLanguage, readonly string[]>> = Object.freeze({
  c: Object.freeze([
    CLANG_COMPRESSED_PACKAGE_SHA256,
    CLANG_PACKAGE_SHA256,
    CLANG_CC1_PINS_SHA256,
    CLANG_MANIFEST_SHA256,
  ]),
  cpp: Object.freeze([
    CLANG_COMPRESSED_PACKAGE_SHA256,
    CLANG_PACKAGE_SHA256,
    CLANG_CC1_PINS_SHA256,
    CLANG_MANIFEST_SHA256,
  ]),
  rust: Object.freeze([
    RUST_COMPRESSED_PACKAGE_SHA256,
    RUST_PACKAGE_SHA256,
    RUST_PACKAGE_MANIFEST_SHA256,
  ]),
  python: Object.freeze([
    PYTHON_COMPRESSED_PACKAGE_SHA256,
    PYTHON_PACKAGE_SHA256,
    PYTHON_PACKAGE_MANIFEST_SHA256,
    PYTHON_RUNTIME_FILES_ARCHIVE_SHA256,
  ]),
  javascript: Object.freeze([TYPESCRIPT_ASSET_SHA256, QUICKJS_ASSET_SHA256]),
  typescript: Object.freeze([TYPESCRIPT_ASSET_SHA256, QUICKJS_ASSET_SHA256]),
  go: Object.freeze([
    GO_COMPRESSED_PACKAGE_SHA256,
    GO_PACKAGE_SHA256,
    GO_PACKAGE_MANIFEST_SHA256,
    GO_COMPRESSED_STANDARD_LIBRARY_SHA256,
    GO_STANDARD_LIBRARY_SHA256,
    GO_COMPILER_SHA256,
    GO_LINKER_SHA256,
  ]),
});

/** Exact executable/compiler content used by cache keys and cost calibration. */
export function toolchainContentIdentity(language: Language): string {
  if (!isBuiltinLanguage(language)) throw new Error(`Forge has no built-in toolchain for '${language}'.`);
  return TOOLCHAIN_CONTENT_SHA256[language].join(".");
}

export function expectedToolchainAssetSha256(assetPath: string): string {
  const normalized = assetPath.startsWith("/") ? assetPath : `/toolchains/${assetPath}`;
  const expected = PINNED_TOOLCHAIN_ASSET_SHA256[normalized];
  if (!expected) throw new Error(`No pinned digest is declared for toolchain asset '${assetPath}'.`);
  return expected;
}

/**
 * Resolves an immutable browser asset request. The digest query is part of the
 * HTTP and Cache Storage key, so rebuilding a same-version asset cannot return
 * bytes cached under an older content identity.
 */
export function contentAddressedToolchainAssetUrl(assetPath: string, assetBaseUrl: URL): URL {
  const sha256 = expectedToolchainAssetSha256(assetPath);
  const base = new URL(assetBaseUrl.href);
  if (!base.pathname.endsWith("/")) base.pathname += "/";
  const inheritedSearch = [...base.searchParams];
  base.search = "";
  const filename = assetPath.slice(assetPath.lastIndexOf("/") + 1);
  const url = new URL(filename, base);
  for (const [name, value] of inheritedSearch) url.searchParams.append(name, value);
  url.searchParams.set("sha256", sha256);
  return url;
}

function freezeToolchain(definition: ToolchainDefinition): Readonly<ToolchainDefinition> {
  return Object.freeze({
    ...definition,
    compilerPackages: Object.freeze([...definition.compilerPackages]),
    targets: Object.freeze([...definition.targets]),
  });
}

export const TOOLCHAINS: Readonly<Record<BuiltinLanguage, Readonly<ToolchainDefinition>>> = Object.freeze({
  c: freezeToolchain({
    language: "c",
    label: "Clang 22",
    artifact: "wasm",
    compilerPackages: [CLANG_PACKAGE],
    targets: ["wasip1", "wasix"],
    version: CLANG_VERSION,
    note: "Native wasip1 module via Clang and LLD; directly executable by WASI and WASIX runtimes.",
  }),
  cpp: freezeToolchain({
    language: "cpp",
    label: "Clang++ 22 (C++20)",
    artifact: "wasm",
    compilerPackages: [CLANG_PACKAGE],
    targets: ["wasip1", "wasix"],
    version: CLANG_VERSION,
    note: "C++20/libc++ wasip1 module; directly executable by WASI and WASIX runtimes.",
  }),
  rust: freezeToolchain({
    language: "rust",
    label: `Rust ${RUST_VERSION}`,
    artifact: "wasm",
    compilerPackages: [`rustc@${RUST_VERSION}#sha256:${RUST_PACKAGE_SHA256}`],
    targets: ["wasip1"],
    version: RUST_VERSION,
    note: "Real rustc, its matching standard library, and a fresh deterministic wasm-ld stage execute as one pinned WebC under Wasmer.",
  }),
  python: freezeToolchain({
    language: "python",
    label: `CPython ${PYTHON_VERSION}`,
    artifact: "runtime-bundle",
    compilerPackages: [PYTHON_PACKAGE],
    runtimePackage: PYTHON_PACKAGE,
    targets: ["wasip1"],
    version: PYTHON_VERSION,
    note: "Byte-compiled project bundled with the source-built CPython wasm32-wasip1 interpreter and standard library.",
  }),
  javascript: freezeToolchain({
    language: "javascript",
    label: "QuickJS-ng",
    artifact: "runtime-bundle",
    compilerPackages: [`typescript@${TYPESCRIPT_VERSION}-wasi`],
    runtimePackage: QUICKJS_PACKAGE,
    targets: ["wasip1"],
    version: QUICKJS_VERSION,
    note: "JavaScript checked by TypeScript/WASI, then executed by the bundled QuickJS-ng/WASI runtime.",
  }),
  typescript: freezeToolchain({
    language: "typescript",
    label: "TypeScript + QuickJS-ng",
    artifact: "runtime-bundle",
    compilerPackages: [`typescript@${TYPESCRIPT_VERSION}-wasi`],
    runtimePackage: QUICKJS_PACKAGE,
    targets: ["wasip1"],
    version: TYPESCRIPT_VERSION,
    note: "The native TypeScript compiler and QuickJS-ng runtime both execute as local WASI modules.",
  }),
  go: freezeToolchain({
    language: "go",
    label: `Go ${GO_VERSION}`,
    artifact: "wasm",
    compilerPackages: [`go@${GO_VERSION}#sha256:${GO_PACKAGE_SHA256}`],
    targets: ["wasip1"],
    version: GO_VERSION,
    note: "The standard Go compiler, linker, and pinned wasip1 standard library execute locally as one WebC under Wasmer.",
  }),
});

export function toolchainCacheIdentity(language: Language) {
  if (!isBuiltinLanguage(language)) throw new Error(`Forge has no built-in toolchain for '${language}'.`);
  const toolchain = TOOLCHAINS[language];
  return {
    forgeContract: FORGE_CONTRACT_VERSION,
    version: toolchain.version,
    compilerPackages: [...toolchain.compilerPackages],
    runtimePackage: toolchain.runtimePackage,
    contentSha256: [...TOOLCHAIN_CONTENT_SHA256[language]],
  };
}

export function toolchainPackageIdentities(language: Language): string[] {
  if (!isBuiltinLanguage(language)) throw new Error(`Forge has no built-in toolchain for '${language}'.`);
  const toolchain = TOOLCHAINS[language];
  return [...new Set([
    ...toolchain.compilerPackages,
    ...(toolchain.runtimePackage ? [toolchain.runtimePackage] : []),
  ])];
}

export function extensionLanguage(path: string): Language | undefined {
  const extension = path.slice(path.lastIndexOf(".") + 1).toLowerCase();
  return ({
    c: "c",
    h: "c",
    cc: "cpp",
    cpp: "cpp",
    cxx: "cpp",
    hpp: "cpp",
    rs: "rust",
    py: "python",
    js: "javascript",
    ts: "typescript",
    go: "go",
  } as Record<string, Language | undefined>)[extension];
}

export function languageLabel(language: Language): string {
  if (!isBuiltinLanguage(language)) return language;
  return ({ c: "C", cpp: "C++", rust: "Rust", python: "Python", javascript: "JavaScript", typescript: "TypeScript", go: "Go" })[language];
}
