import { isBuiltinLanguage, type BuiltinLanguage, type Language, type TargetAbi } from "./types.ts";
import { WASM_OJ_CONTRACT_VERSION } from "./contract.ts";

export interface ToolchainDefinition {
  readonly language: BuiltinLanguage;
  readonly label: string;
  readonly artifact: "wasm" | "runtime-bundle";
  readonly compilerPackages: readonly string[];
  readonly runtimePackage?: string;
  readonly targets: readonly TargetAbi[];
  readonly version: string;
  readonly note: string;
}

export const CLANG_VERSION = "22.0.0-git20542-10";
export const CLANG_PACKAGE = `wasm-oj/clang@${CLANG_VERSION}`;
export const CLANG_PACKAGE_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.webc.gz.bin`;
export const CLANG_CC1_PINS_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.cc1-pins.json`;
export const CLANG_MANIFEST_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.manifest.json`;
export const CLANG_LIBCXX_PCH_MANIFEST_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.libcxx-pch.json`;
export const CLANG_LIBCXX_PCH_DEBUG_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.cpp-debug.pch.gz.bin`;
export const CLANG_LIBCXX_PCH_RELEASE_ASSET_PATH = `/toolchains/clang-${CLANG_VERSION}.cpp-release.pch.gz.bin`;
export const CLANG_COMPRESSED_PACKAGE_SHA256 = "7f10d90b8e52b270f04874641a1d0bf9e94e85b4f6c7573a774cebbc6d32552a";
/** SHA-256 after browser-side gzip decompression. */
export const CLANG_PACKAGE_SHA256 = "21ded33b9c6d4e1aaad5528c940bdaf6c3e84be77ea8f522f018ca7289a2a224";
/** SHA-256 of the pinned cc1/wasm-ld argv manifest; regenerated by scripts/pin-clang-cc1-argv.mjs. */
export const CLANG_CC1_PINS_SHA256 = "66c4604dccd3f89d8e1472bf4432367d7396cce4a01279b1a1db445f229dba72";
export const CLANG_MANIFEST_SHA256 = "6382dcdfb6a2da49032a0e08da3b1fb490eb24432be85c3c12e3e871a5065273";
/** Updated atomically with the generated toolchain-admitted PCH assets. */
export const CLANG_LIBCXX_PCH_MANIFEST_SHA256 = "d126c99e951a7302d4ea2b66da4ed64d3d74e9d319d562518867c8d8c97a06b8";
export const CLANG_LIBCXX_PCH = Object.freeze({
  "cpp-debug": Object.freeze({
    path: CLANG_LIBCXX_PCH_DEBUG_ASSET_PATH,
    sha256: "05a4db721448ba33e65977cb4ac366908ea215ab377e3b6d09f1fd224d515b68",
    compressedSha256: "a4152027d248412eca8aec3e7e23f6f7c81f95170cae9fd385bcf02e57e91fc9",
  }),
  "cpp-release": Object.freeze({
    path: CLANG_LIBCXX_PCH_RELEASE_ASSET_PATH,
    sha256: "aec9e778ac527c120ba369b9b0e142cf8206d11365801208847ba0e1c39daa1a",
    compressedSha256: "18f4ca8ab8ca7888db572ba34146fc1acb213a7e7305000ea6285188f52f99f4",
  }),
} as const);
export const PYTHON_VERSION = "3.14.6";
export const PYTHON_PACKAGE_SHA256 = "454ffc53936aa13a0d7f4afbb5bd50ada339c8ebd04bbf27ea19e4104cf43207";
export const PYTHON_PACKAGE_SPECIFIER = `wasm-oj/cpython@${PYTHON_VERSION}`;
export const PYTHON_PACKAGE = `${PYTHON_PACKAGE_SPECIFIER}#sha256:${PYTHON_PACKAGE_SHA256}`;
export const PYTHON_PACKAGE_ASSET_PATH = `/toolchains/python-${PYTHON_VERSION}-wasip1.webc.gz.bin`;
export const PYTHON_PACKAGE_MANIFEST_ASSET_PATH = `/toolchains/python-${PYTHON_VERSION}-wasip1.manifest.json`;
export const PYTHON_COMPRESSED_PACKAGE_SHA256 = "218cd20ac4abb443e0700816010a615a345a43eae623a0232da2227135a6c7a6";
export const PYTHON_PACKAGE_MANIFEST_SHA256 = "054eccad04a7cee7ba1661062142ef0d639976850981eab8fc785f48eb26129e";
export const PYTHON_RUNTIME_FILES_ARCHIVE_SHA256 = "44d894f91487f20c2bb04fe496a9343db37d8720fb706472c2b4a7f3300db039";
export const QUICKJS_VERSION = "0.15.1";
export const QUICKJS_PACKAGE = `wasm-oj/quickjs-ng@${QUICKJS_VERSION}`;
export const QUICKJS_ASSET_PATH = `/toolchains/quickjs-${QUICKJS_VERSION}.wasm.gz.bin`;
export const QUICKJS_ASSET_SHA256 = "8c7f0588210490e7d77f198fc91f72c1b94787ab4c359c4786ca59a363c4f5e8";
export const TYPESCRIPT_VERSION = "7.0.2";
export const TYPESCRIPT_ASSET_PATH = `/toolchains/typescript-${TYPESCRIPT_VERSION}.wasm.gz.bin`;
export const TYPESCRIPT_ASSET_SHA256 = "06e58ce887d95d1895055699b8dc96a1cde7d1f2baa48de40f9b790e3271dc16";
export const RUST_VERSION = "1.91.1-dev";
export const RUST_PACKAGE_ASSET_PATH = `/toolchains/rust-${RUST_VERSION}.webc.gz.bin`;
export const RUST_PACKAGE_MANIFEST_ASSET_PATH = `/toolchains/rust-${RUST_VERSION}.manifest.json`;
export const RUST_COMPRESSED_PACKAGE_SHA256 = "cfbdadc67be1315e735aa55bdf8a5a0d00171982a023fefcf7ba586127753887";
/** SHA-256 after browser-side gzip decompression. */
export const RUST_PACKAGE_SHA256 = "765de8d68d03078e79f69f49dec0dcab1ff96fe3bbe5e9eafebb2ce61a39d3ee";
export const RUST_PACKAGE_MANIFEST_SHA256 = "d5bbdca994e61888679c5738cb9420649c0854ed0eb5d65468bc67d5d550bce1";
export const GO_VERSION = "1.26.5";
export const GO_PACKAGE_ASSET_PATH = `/toolchains/go-${GO_VERSION}-wasip1.webc.gz.bin`;
export const GO_PACKAGE_MANIFEST_ASSET_PATH = `/toolchains/go-${GO_VERSION}-wasip1.manifest.json`;
export const GO_STANDARD_LIBRARY_ASSET_PATH = `/toolchains/go-${GO_VERSION}-wasip1.stdlib.gz.bin`;
export const GO_COMPRESSED_PACKAGE_SHA256 = "70a7e359884b09b2e1a622d6ac5cd6e31c334aab519e6dd80dff5e040a9e09e4";
export const GO_PACKAGE_SHA256 = "c3a97934b6a83fefdea5c31f99141f70f76189eedc9ec0fa9ccd41302e50963b";
export const GO_PACKAGE_MANIFEST_SHA256 = "5d784e9ca640b9525e84b598c0beb97ca110ae908568ca45f6441a441d99a262";
export const GO_COMPRESSED_STANDARD_LIBRARY_SHA256 = "aeffc384fdc624544f174ba5fc3c22395717fdbc3c4387d677d20855b6be80d8";
export const GO_STANDARD_LIBRARY_SHA256 = "e1ec64b08efd02b35b7ffdaf3970875aaae98325fa4795eafca94ebae2d0d192";
export const GO_COMPILER_SHA256 = "9e557f5b86961fd604217d7521461c5d2b7322e383fa30dead5669b77db12201";
export const GO_LINKER_SHA256 = "2eefca10af935a307ab7946447146bd30e0ea0fb5460be54dc1c55844d155580";
export const JAVA_VERSION = "teavm-0.13.1-wasi";
export const JAVA_COMPILER_PACKAGE = `wasm-oj/java-teavm@${JAVA_VERSION}`;
export const JAVA_COMPILER_ASSET_PATH = "/toolchains/java-teavm-0.13.1.wasi.compiler.webc.gz.bin";
export const JAVA_COMPILE_CLASSLIB_ASSET_PATH = "/toolchains/java-teavm-0.13.1.compile-classlib.bin";
export const JAVA_RUNTIME_CLASSLIB_ASSET_PATH = "/toolchains/java-teavm-0.13.1.runtime-classlib.bin";
export const JAVA_COMPILER_COMPRESSED_PACKAGE_SHA256 = "129f1f51d591e58954f88787d36396b856a9a68ba3ae9c9d14f20bd67c2c7722";
export const JAVA_COMPILER_PACKAGE_SHA256 = "f8f86761cf31062565187e4a66f73b6903f257fe84c0ce70ea1cd28441b6c2e9";
export const JAVA_COMPILER_SHA256 = "33a0d662395256f10a5d02ea305fc7b18007b2b8fe8996859017b084d3d19735";
export const JAVA_COMPILE_CLASSLIB_SHA256 = "acfe3fb09e5f2c0c7c8dc2339c66fcdadc1f8e1bf1c74be446926175ef770868";
export const JAVA_RUNTIME_CLASSLIB_SHA256 = "21a9394586e416af2fca4eb0ed08521cbc8924e1d1afaa07863a59a3cfae54ab";

export const PINNED_TOOLCHAIN_ASSET_SHA256 = Object.freeze<Record<string, string>>({
  [CLANG_PACKAGE_ASSET_PATH]: CLANG_COMPRESSED_PACKAGE_SHA256,
  [CLANG_CC1_PINS_ASSET_PATH]: CLANG_CC1_PINS_SHA256,
  [CLANG_MANIFEST_ASSET_PATH]: CLANG_MANIFEST_SHA256,
  [CLANG_LIBCXX_PCH_MANIFEST_ASSET_PATH]: CLANG_LIBCXX_PCH_MANIFEST_SHA256,
  [CLANG_LIBCXX_PCH_DEBUG_ASSET_PATH]: CLANG_LIBCXX_PCH["cpp-debug"].compressedSha256,
  [CLANG_LIBCXX_PCH_RELEASE_ASSET_PATH]: CLANG_LIBCXX_PCH["cpp-release"].compressedSha256,
  [PYTHON_PACKAGE_ASSET_PATH]: PYTHON_COMPRESSED_PACKAGE_SHA256,
  [PYTHON_PACKAGE_MANIFEST_ASSET_PATH]: PYTHON_PACKAGE_MANIFEST_SHA256,
  [QUICKJS_ASSET_PATH]: QUICKJS_ASSET_SHA256,
  [TYPESCRIPT_ASSET_PATH]: TYPESCRIPT_ASSET_SHA256,
  [RUST_PACKAGE_ASSET_PATH]: RUST_COMPRESSED_PACKAGE_SHA256,
  [RUST_PACKAGE_MANIFEST_ASSET_PATH]: RUST_PACKAGE_MANIFEST_SHA256,
  [GO_PACKAGE_ASSET_PATH]: GO_COMPRESSED_PACKAGE_SHA256,
  [GO_PACKAGE_MANIFEST_ASSET_PATH]: GO_PACKAGE_MANIFEST_SHA256,
  [GO_STANDARD_LIBRARY_ASSET_PATH]: GO_COMPRESSED_STANDARD_LIBRARY_SHA256,
  [JAVA_COMPILER_ASSET_PATH]: JAVA_COMPILER_COMPRESSED_PACKAGE_SHA256,
  [JAVA_COMPILE_CLASSLIB_ASSET_PATH]: JAVA_COMPILE_CLASSLIB_SHA256,
  [JAVA_RUNTIME_CLASSLIB_ASSET_PATH]: JAVA_RUNTIME_CLASSLIB_SHA256,
});

const TOOLCHAIN_CONTENT_SHA256: Readonly<Record<BuiltinLanguage, readonly string[]>> = Object.freeze({
  c: Object.freeze([
    CLANG_COMPRESSED_PACKAGE_SHA256,
    CLANG_PACKAGE_SHA256,
    CLANG_CC1_PINS_SHA256,
    CLANG_MANIFEST_SHA256,
  ]),
  cpp: Object.freeze([
    CLANG_COMPRESSED_PACKAGE_SHA256,
    CLANG_PACKAGE_SHA256,
    CLANG_CC1_PINS_SHA256,
    CLANG_MANIFEST_SHA256,
  ]),
  rust: Object.freeze([
    RUST_COMPRESSED_PACKAGE_SHA256,
    RUST_PACKAGE_SHA256,
    RUST_PACKAGE_MANIFEST_SHA256,
  ]),
  python: Object.freeze([
    PYTHON_COMPRESSED_PACKAGE_SHA256,
    PYTHON_PACKAGE_SHA256,
    PYTHON_PACKAGE_MANIFEST_SHA256,
    PYTHON_RUNTIME_FILES_ARCHIVE_SHA256,
  ]),
  javascript: Object.freeze([TYPESCRIPT_ASSET_SHA256, QUICKJS_ASSET_SHA256]),
  typescript: Object.freeze([TYPESCRIPT_ASSET_SHA256, QUICKJS_ASSET_SHA256]),
  go: Object.freeze([
    GO_COMPRESSED_PACKAGE_SHA256,
    GO_PACKAGE_SHA256,
    GO_PACKAGE_MANIFEST_SHA256,
    GO_COMPRESSED_STANDARD_LIBRARY_SHA256,
    GO_STANDARD_LIBRARY_SHA256,
    GO_COMPILER_SHA256,
    GO_LINKER_SHA256,
  ]),
});

/** Exact executable/compiler content used by cache keys and cost calibration. */
export function toolchainContentIdentity(language: Language): string {
  if (language === "java") {
    return [
      JAVA_COMPILER_COMPRESSED_PACKAGE_SHA256,
      JAVA_COMPILER_PACKAGE_SHA256,
      JAVA_COMPILER_SHA256,
      JAVA_COMPILE_CLASSLIB_SHA256,
      JAVA_RUNTIME_CLASSLIB_SHA256,
    ].join(".");
  }
  if (!isBuiltinLanguage(language)) throw new Error(`WASM-OJ has no built-in toolchain for '${language}'.`);
  return TOOLCHAIN_CONTENT_SHA256[language].join(".");
}

export function expectedToolchainAssetSha256(assetPath: string): string {
  const normalized = assetPath.startsWith("/") ? assetPath : `/toolchains/${assetPath}`;
  const expected = PINNED_TOOLCHAIN_ASSET_SHA256[normalized];
  if (!expected) throw new Error(`No pinned digest is declared for toolchain asset '${assetPath}'.`);
  return expected;
}

/**
 * Resolves an immutable browser asset request. The digest query is part of the
 * HTTP and Cache Storage key, so rebuilding a same-version asset cannot return
 * bytes cached under an older content identity.
 */
export function contentAddressedToolchainAssetUrl(assetPath: string, assetBaseUrl: URL): URL {
  const sha256 = expectedToolchainAssetSha256(assetPath);
  const base = new URL(assetBaseUrl.href);
  if (!base.pathname.endsWith("/")) base.pathname += "/";
  const inheritedSearch = [...base.searchParams];
  base.search = "";
  const filename = assetPath.slice(assetPath.lastIndexOf("/") + 1);
  const url = new URL(filename, base);
  for (const [name, value] of inheritedSearch) url.searchParams.append(name, value);
  url.searchParams.set("sha256", sha256);
  return url;
}

function freezeToolchain(definition: ToolchainDefinition): Readonly<ToolchainDefinition> {
  return Object.freeze({
    ...definition,
    compilerPackages: Object.freeze([...definition.compilerPackages]),
    targets: Object.freeze([...definition.targets]),
  });
}

export const TOOLCHAINS: Readonly<Record<BuiltinLanguage, Readonly<ToolchainDefinition>>> = Object.freeze({
  c: freezeToolchain({
    language: "c",
    label: "Clang 22",
    artifact: "wasm",
    compilerPackages: [CLANG_PACKAGE],
    targets: ["wasip1", "wasix"],
    version: CLANG_VERSION,
    note: "Native wasip1 module via Clang and LLD; directly executable by WASI and WASIX runtimes.",
  }),
  cpp: freezeToolchain({
    language: "cpp",
    label: "Clang++ 22 (C++20)",
    artifact: "wasm",
    compilerPackages: [CLANG_PACKAGE],
    targets: ["wasip1", "wasix"],
    version: CLANG_VERSION,
    note: "C++20/libc++ wasip1 module; directly executable by WASI and WASIX runtimes.",
  }),
  rust: freezeToolchain({
    language: "rust",
    label: `Rust ${RUST_VERSION}`,
    artifact: "wasm",
    compilerPackages: [`rustc@${RUST_VERSION}#sha256:${RUST_PACKAGE_SHA256}`],
    targets: ["wasip1"],
    version: RUST_VERSION,
    note: "Real rustc, its matching standard library, and a fresh deterministic wasm-ld stage execute as one pinned WebC under Wasmer.",
  }),
  python: freezeToolchain({
    language: "python",
    label: `CPython ${PYTHON_VERSION}`,
    artifact: "runtime-bundle",
    compilerPackages: [PYTHON_PACKAGE],
    runtimePackage: PYTHON_PACKAGE,
    targets: ["wasip1"],
    version: PYTHON_VERSION,
    note: "Byte-compiled project bundled with the source-built CPython wasm32-wasip1 interpreter and standard library.",
  }),
  javascript: freezeToolchain({
    language: "javascript",
    label: "QuickJS-ng",
    artifact: "runtime-bundle",
    compilerPackages: [`typescript@${TYPESCRIPT_VERSION}-wasi`],
    runtimePackage: QUICKJS_PACKAGE,
    targets: ["wasip1"],
    version: QUICKJS_VERSION,
    note: "JavaScript checked by TypeScript/WASI, then executed by the bundled QuickJS-ng/WASI runtime.",
  }),
  typescript: freezeToolchain({
    language: "typescript",
    label: "TypeScript + QuickJS-ng",
    artifact: "runtime-bundle",
    compilerPackages: [`typescript@${TYPESCRIPT_VERSION}-wasi`],
    runtimePackage: QUICKJS_PACKAGE,
    targets: ["wasip1"],
    version: TYPESCRIPT_VERSION,
    note: "The native TypeScript compiler and QuickJS-ng runtime both execute as local WASI modules.",
  }),
  go: freezeToolchain({
    language: "go",
    label: `Go ${GO_VERSION}`,
    artifact: "wasm",
    compilerPackages: [`go@${GO_VERSION}#sha256:${GO_PACKAGE_SHA256}`],
    targets: ["wasip1"],
    version: GO_VERSION,
    note: "The standard Go compiler, linker, and pinned wasip1 standard library execute locally as one WebC under Wasmer.",
  }),
});

export function toolchainCacheIdentity(language: Language) {
  if (language === "java") {
    return {
      wasmOjContract: WASM_OJ_CONTRACT_VERSION,
      version: JAVA_VERSION,
      compilerPackages: [JAVA_COMPILER_PACKAGE],
      contentSha256: toolchainContentIdentity(language).split("."),
    };
  }
  if (!isBuiltinLanguage(language)) throw new Error(`WASM-OJ has no built-in toolchain for '${language}'.`);
  const toolchain = TOOLCHAINS[language];
  return {
    wasmOjContract: WASM_OJ_CONTRACT_VERSION,
    version: toolchain.version,
    compilerPackages: [...toolchain.compilerPackages],
    runtimePackage: toolchain.runtimePackage,
    contentSha256: [...TOOLCHAIN_CONTENT_SHA256[language]],
  };
}

export function toolchainPackageIdentities(language: Language): string[] {
  if (language === "java") return [JAVA_COMPILER_PACKAGE];
  if (!isBuiltinLanguage(language)) throw new Error(`WASM-OJ has no built-in toolchain for '${language}'.`);
  const toolchain = TOOLCHAINS[language];
  return [...new Set([
    ...toolchain.compilerPackages,
    ...(toolchain.runtimePackage ? [toolchain.runtimePackage] : []),
  ])];
}

export function extensionLanguage(path: string): Language | undefined {
  const extension = path.slice(path.lastIndexOf(".") + 1).toLowerCase();
  return ({
    c: "c",
    h: "c",
    cc: "cpp",
    cpp: "cpp",
    cxx: "cpp",
    hpp: "cpp",
    rs: "rust",
    py: "python",
    js: "javascript",
    ts: "typescript",
    go: "go",
    java: "java",
  } as Record<string, Language | undefined>)[extension];
}

export function languageLabel(language: Language): string {
  if (language === "java") return "Java";
  if (!isBuiltinLanguage(language)) return language;
  return ({ c: "C", cpp: "C++", rust: "Rust", python: "Python", javascript: "JavaScript", typescript: "TypeScript", go: "Go", java: "Java" })[language];
}
